### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by s31064** [EvotecIT/IISParser#1]
The ability to filter the IIS Properties and also output the log to a csv file would pretty much make this perfect.

**Comment by PrzemyslawKlys** [comment]
The thing is you should probably just use `Get-IISParsedLog -FilePath "C:\Support\GitHub\IISParser\Ignore\u_ex220507.log" -First 1 -Skip 1 | Select-Object -Property XXXX | Export-CSV -NoTypeInformation -Path XXX` 

I don't think it's necessary to complicate this query.
